### ISSUE TITLE
Error when deploying walkthrough: Project name could not be inferred

### ISSUE THREAD

**Issue by chrisvxd** [saasify-sh/saasify#1]
Following the steps in [the Walkthrough](https://functional-income.com/walkthrough), I hit this bug when running `fin deploy`:

```
/Users/chrisvilla/.nvm/versions/node/v9.11.2/lib/node_modules/fin/node_modules/conf/index.js:56
				throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
				^
Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Conf (/Users/chrisvilla/.nvm/versions/node/v9.11.2/lib/node_modules/fin/node_modules/conf/index.js:56:11)
    at Object.<anonymous> (/Users/chrisvilla/.nvm/versions/node/v9.11.2/lib/node_modules/fin/lib/auth.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/chrisvilla/.nvm/versions/node/v9.11.2/lib/node_modules/fin/lib/cli.js:8:14)```

**Comment by chrisvxd** [comment]
Upon further investigation, it turns out fin requires `package.json` but walkthrough just specifies "Create a new directory containing these two files", and doesn't mention package.json.

**Comment by transitive-bullshit** [comment]
This should be fixed now :)
